### ISSUE TITLE
Check panic in Google Cloud Platform Cloud Shell

### ISSUE THREAD

**Issue by HeavyWombat** [homeport/gonut#95]
```
# gonut push go
panic: runtime error: slice bounds out of range
goroutine 20 [running]:
github.com/gonvenience/bunt.(*String).Substring(...)
        /home/travis/gopath/pkg/mod/github.com/gonvenience/bunt@v1.1.1/model.go:46
github.com/gonvenience/bunt.Substring(0xc000026800, 0x20, 0x0, 0xffffffffffffffe4, 0xc000002819, 0x3)
        /home/travis/gopath/pkg/mod/github.com/gonvenience/bunt@v1.1.1/convenience.go:65 +0xf7
github.com/gonvenience/text.FixedLength(0xc000026800, 0x20, 0xffffffffffffffea, 0x3, 0x3fda5a5a5a5a5a5a)
        /home/travis/gopath/pkg/mod/github.com/gonvenience/text@v1.0.2/text.go:80 +0x78
github.com/gonvenience/wait.(*ProgressIndicator).Start.func1(0xc0001d2100)
        /home/travis/gopath/pkg/mod/github.com/gonvenience/wait@v1.0.2/wait.go:145 +0xaf
created by github.com/gonvenience/wait.(*ProgressIndicator).Start
        /home/travis/gopath/pkg/mod/github.com/gonvenience/wait@v1.0.2/wait.go:120 +0xf3
```

```
TERM=screen
```

**Comment by HeavyWombat** [comment]
Fixed with https://github.com/gonvenience/text/commit/8b8c5ed1deb5713c04974878a0d047ad908ade59
